Dashboard page
aryatrading/arya-crypto-web pull request #15
Opened 2023-04-28 11:57 UTC by almujtabamohammed

2023-04-28 12:32 UTC, AbdallaEmadEldinAbdalla commented on src/components/shared/layout/flex.type.ts
> +import { HTMLAttributes } from "react";
Both on one import!

2023-04-28 13:42 UTC, AbdallaEmadEldinAbdalla requested changes
Please fix comments

2023-04-28 13:42 UTC, AbdallaEmadEldinAbdalla commented on src/components/app/dashboard/dashboard.module.scss
> +            border-bottom: 1px solid #1C1C1C;
Please use the colors from tailwind

2023-04-28 13:42 UTC, AbdallaEmadEldinAbdalla commented on src/components/app/dashboard/dashboard.module.scss
> +    min-width: 800px;
Why we have min width as 800px! 
how it will be displayed in small screens preview.

2023-04-28 13:42 UTC, AbdallaEmadEldinAbdalla commented on src/components/app/dashboard/dashboard.tsx
> +    useEffect(() => {
Why we have 2 useEffect with the same deps please combine them

2023-04-28 13:42 UTC, AbdallaEmadEldinAbdalla commented on src/components/app/dashboard/dashboard.tsx
> +    useEffect(() => {
Init the state with true value and delete this part you already call it with every exchange change.

2023-04-28 13:42 UTC, AbdallaEmadEldinAbdalla commented on src/components/app/dashboard/dashboard.tsx
> +                            <th>Amount</th>
Please apply translation here.

2023-04-28 13:42 UTC, AbdallaEmadEldinAbdalla commented on src/components/app/dashboard/dashboard.tsx
> +    console.log({ isLoadingPortfolioSnapshots, isLoadingPortfolioHoldings, exchangeStoreStatus })
Please remove this console.

2023-04-28 13:42 UTC, AbdallaEmadEldinAbdalla commented on src/components/shared/charts/doughnut/doughnut.tsx
> +// import "./PieCharts.scss";
Please remove the commented code.

2023-04-28 13:42 UTC, AbdallaEmadEldinAbdalla commented on src/components/shared/form/table/table.tsx
> +                <tr>
@almujtabamohammed

2023-04-28 13:42 UTC, AbdallaEmadEldinAbdalla commented on src/components/shared/charts/graph/graph.tsx
> +                    background: { type: ColorType.Solid, color: '#00000000' },
@almujtabamohammed

2023-04-28 13:42 UTC, AbdallaEmadEldinAbdalla commented on src/components/shared/charts/doughnut/doughnut.tsx
> +const colors: string[] = ['pink', 'orange', 'blue', 'darkBlue', 'indigo', 'lime', 'purple', 'green', 'yellow', 'amber', 'red', 'cyan', 'brown', 'teal', 'grey', 'lime', 'blueGrey'];
@almujtabamohammed

2023-04-28 13:42 UTC, AbdallaEmadEldinAbdalla commented on src/components/app/dashboard/dashboard.module.scss
> +            border-bottom: 1px solid #1C1C1C;
@almujtabamohammed

2023-04-28 13:42 UTC, AbdallaEmadEldinAbdalla commented on src/components/app/dashboard/dashboard.module.scss
> +    min-width: 800px;
@almujtabamohammed

2023-04-28 13:42 UTC, AbdallaEmadEldinAbdalla commented on src/components/app/dashboard/dashboard.tsx
> +    useEffect(() => {
@almujtabamohammed

2023-04-28 13:42 UTC, AbdallaEmadEldinAbdalla commented on src/components/app/dashboard/dashboard.tsx
> +    useEffect(() => {
@almujtabamohammed

2023-04-28 13:42 UTC, AbdallaEmadEldinAbdalla commented on src/components/app/dashboard/dashboard.tsx
> +                            <th>Amount</th>
@almujtabamohammed

2023-04-28 13:42 UTC, AbdallaEmadEldinAbdalla commented on src/components/app/dashboard/dashboard.tsx
> +    console.log({ isLoadingPortfolioSnapshots, isLoadingPortfolioHoldings, exchangeStoreStatus })
@almujtabamohammed

2023-04-28 13:42 UTC, AbdallaEmadEldinAbdalla commented on src/components/shared/charts/doughnut/doughnut.tsx
> +// import "./PieCharts.scss";
@almujtabamohammed

2023-05-01 06:49 UTC, almujtabamohammed commented on src/components/app/dashboard/dashboard.module.scss
> +    min-width: 800px;
It will overflow with scroll on small screens

2023-05-01 06:56 UTC, merged