edit-smart-alloc-table revert and misc
aryatrading/arya-crypto-web pull request #206
Opened 2023-08-04 07:09 UTC by ameer-greenbull

## Description

- fixed light mode for post in asset information
- fixed worth in asset holdings 
- reverted table in edit smartallocation due to slider Issue

2023-08-04 07:14 UTC, almujtabamohammed requested changes

2023-08-04 07:14 UTC, almujtabamohammed commented on src/components/app/smart-allocation/edit-smart-allocation/edit-smart-allocation.tsx
> +                                    }
use `asset.pnl.percentage` to get the percentage change in the last 24 h

2023-08-04 07:14 UTC, almujtabamohammed commented on package.json
> +    "react-slider": "^2.0.6",
Remove react slider if you are not using it

2023-08-07 10:28 UTC, alex-greenbull commented
@ameer-greenbull @almujtabamohammed we need this to go to Prod

2023-08-07 10:40 UTC, merged