Feature/asset holdings
aryatrading/arya-crypto-web pull request #22
Opened 2023-05-03 13:01 UTC by SNuseibeh

2023-05-05 12:35 UTC, almujtabamohammed requested changes
Assets page isn't responsive

2023-05-05 12:35 UTC, almujtabamohammed commented on src/utils/constants/assetTimeseries.ts
> +    value: "tradingview",
Translate

2023-05-05 12:35 UTC, almujtabamohammed commented on src/components/shared/tables/exchangeHoldingTable.tsx
> +                </td>
elm.avg_price is always 0?

2023-05-05 12:35 UTC, almujtabamohammed commented on src/components/shared/tables/assetOrders.tsx
> +    t("amount"),
Replace the 2nd "amount" with price

2023-05-08 05:53 UTC, SNuseibeh commented on src/utils/constants/assetTimeseries.ts
> +    value: "tradingview",
Not used in the app, removed from codebase

2023-05-08 05:59 UTC, SNuseibeh commented on src/components/shared/containers/asset/assetVote.tsx
>            title="Bullish"
this is handled with the voting PR

2023-05-09 07:03 UTC, merged