Feature/community/post trade
aryatrading/arya-crypto-web pull request #232
Opened 2023-08-31 04:39 UTC by almujtabamohammed

2023-09-19 06:34 UTC, AbdallaEmadEldinAbdalla requested changes

2023-09-19 06:34 UTC, AbdallaEmadEldinAbdalla commented on src/components/app/community/Post/PostContent/PostFinancialData/FinancialDataPopup/FinancialDataPopup.tsx
> +            console.log({ chartData })
Delete console

2023-09-19 06:34 UTC, AbdallaEmadEldinAbdalla commented on src/components/shared/charts/graph/candlesticksChart.tsx
> +            console.log({ markers }, financialData.PriceEvaluations)
Delete console

2023-09-19 06:34 UTC, AbdallaEmadEldinAbdalla commented on src/components/shared/charts/graph/candlesticksChart.tsx
> +                    <p className="text-2xl font-bold">Calculating...</p>
Translate

2023-09-19 06:34 UTC, AbdallaEmadEldinAbdalla commented on src/services/controllers/asset.tsx
> +  return await axios.get(`${process.env.NEXT_PUBLIC_TWELEVE_API_URL}?symbol=${symbol}/usd&interval=8h&outputsize=21&apikey=${process.env.NEXT_PUBLIC_TWELVE_DATA_API_KEY}&timezone=UTC`)
Revert this change it ruining the community search and market asset page result

2023-09-20 06:48 UTC, AbdallaEmadEldinAbdalla requested changes

2023-09-20 06:48 UTC, AbdallaEmadEldinAbdalla commented on src/components/app/community/Post/PostContent/PostFinancialData/FinancialDataPopup/FinancialDataPopup.tsx
> +        show ? <Modal
Why `show` is outside! xD

2023-09-21 05:14 UTC, almujtabamohammed commented on src/components/app/community/Post/PostContent/PostFinancialData/FinancialDataPopup/FinancialDataPopup.tsx
> +        show ? <Modal
To reset the state inside the Modal

2023-09-21 06:43 UTC, merged