Feature/nav search bar crw 106
aryatrading/arya-crypto-web pull request #25
Opened 2023-05-08 11:26 UTC by AbdallaEmadEldinAbdalla

[CRW-106](https://techxarya.atlassian.net/browse/CRW-106)

pref: Implement asset search inside nav-bar.

2023-05-08 12:11 UTC, almujtabamohammed requested changes
Fix responsiveness

2023-05-08 12:11 UTC, almujtabamohammed commented on src/components/shared/assetDropdown/index.tsx
> +                            {showContentHeaderLabel && <h3 className="font-extrabold text-white text-xl">{contentHeaderLabel || t('selectAsset')}</h3>}
Fix translation for "selectAsset"

2023-05-08 12:21 UTC, AbdallaEmadEldinAbdalla commented
> Fix responsiveness

@almujtabamohammed  i don't have any design for the mobile view.

2023-05-08 12:25 UTC, almujtabamohammed commented
> > Fix responsiveness
> 
> @almujtabamohammed i don't have any design for the mobile view.

2023-05-08 12:28 UTC, almujtabamohammed commented
> > Fix responsiveness
> 
> @almujtabamohammed i don't have any design for the mobile view.

Can you check with Daryl and Alex, because it's not usable right now on mobile

2023-05-09 07:21 UTC, almujtabamohammed approved these changes

2023-05-09 07:22 UTC, merged