terms and conditions done
aryatrading/arya-crypto-web pull request #316
Opened 2023-09-28 13:30 UTC by ameer-greenbull

## Description

## Related to

## Solution

## Checklist:

- [ ] I have updated the app changelog
- [ ] I have made corresponding changes to the documentation
- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have performed a self-review of my own code
- [ ] My changes generate no new warnings on the linter

2023-10-02 06:47 UTC, AbdallaEmadEldinAbdalla approved these changes

2023-10-03 11:22 UTC, almujtabamohammed requested changes

2023-10-03 11:22 UTC, almujtabamohammed commented on src/pages/terms-and-conditions/terms.css
Remove file

2023-10-03 11:22 UTC, almujtabamohammed commented on src/pages/terms-and-conditions/index.tsx
Exclude from weglot translation

2023-10-03 11:22 UTC, almujtabamohammed commented on src/pages/legal-notice/index.tsx
Exclude from weglot translation

2023-10-04 05:14 UTC, almujtabamohammed approved these changes

2023-10-04 05:17 UTC, merged