Feature/asset trade
aryatrading/arya-crypto-web pull request #32
Opened 2023-05-10 13:42 UTC by SNuseibeh

2023-05-11 11:33 UTC, alex-greenbull commented
Why are you merging into Master?

2023-05-11 13:32 UTC, alex-greenbull commented
@SNuseibeh 
![Screenshot_localhost3000assetsymbolbtc_001276](https://github.com/aryatrading/arya-crypto-web/assets/58027479/bd2e4b1a-33de-4f11-b530-3477a179e8a5)
this looks messed up

Ameer and Abdallah both made asset selection dropdown / modal, maybe see with them to unify into one component

2023-05-11 13:37 UTC, alex-greenbull commented
@SNuseibeh 
![Screenshot_localhost3000assetsymbolbtc_001280](https://github.com/aryatrading/arya-crypto-web/assets/58027479/8c166090-6b0e-420d-a84e-783e64b83b62)
 
 this should be an input too, entering a value here would calculate the correct value in USDT

2023-05-11 13:39 UTC, alex-greenbull commented
@SNuseibeh wheres the exchange selector

2023-05-12 06:56 UTC, AbdallaEmadEldinAbdalla requested changes

2023-05-12 06:56 UTC, AbdallaEmadEldinAbdalla commented on src/components/app/trade/assetTrade.tsx
> +          <p className="mt-2 text-center font-semibold text-sm ">Advance Mode</p>
Apply translation.

2023-05-12 06:56 UTC, AbdallaEmadEldinAbdalla commented on src/components/app/trade/assetTrade.tsx
> +          onClick={() => onTradePress()}
No need to be an arrow function just pass the function name like `={onTradePress}`

2023-05-12 06:56 UTC, AbdallaEmadEldinAbdalla commented on src/components/app/trade/assetTrade.tsx
> +  const onTradePress = async () => {
it's better to use `useCallback` and `useMemo` instead of the normal arrow function.

2023-05-12 06:56 UTC, AbdallaEmadEldinAbdalla commented on src/components/app/trade/assetTradeFromInput.tsx
> +        <p className="font-medium text-gray-500 text-sm">From</p>
Apply translation

2023-05-12 06:56 UTC, AbdallaEmadEldinAbdalla commented on src/components/app/trade/assetTradeFromInput.tsx
> +        <p className="font-medium text-gray-500 text-sm">From</p>
Use colors from our custom palette.

2023-05-12 06:56 UTC, AbdallaEmadEldinAbdalla commented on src/components/app/trade/assetTradeFromInput.tsx
> +            title="Max"
- Apply translation.
- call the function directly without arrow function.

2023-05-12 06:56 UTC, AbdallaEmadEldinAbdalla commented on src/components/app/trade/assetTradeToInput.tsx
> +  const qty =
Use `useMemo` here.

2023-05-12 06:56 UTC, AbdallaEmadEldinAbdalla commented on src/components/app/trade/assetTradeToInput.tsx
> +          Price ~{" "}
Apply translation

2023-05-12 06:56 UTC, AbdallaEmadEldinAbdalla commented on src/components/app/trade/assetTradeToInput.tsx
> +import { FC, useMemo } from "react";
Why we have 2 components for the same feature?

we can use 1 and modify the content passed on props.

2023-05-12 06:56 UTC, AbdallaEmadEldinAbdalla commented on src/components/shared/containers/asset/assetDetailsHeader.tsx
> +          onClick={() => null}
Why we have it if it's null?

2023-05-12 06:56 UTC, AbdallaEmadEldinAbdalla commented on src/components/shared/containers/asset/assetDetailsHeader.tsx
> +          onClick={() => null}
Why we have it if it's null?

2023-05-12 06:56 UTC, AbdallaEmadEldinAbdalla commented on src/services/redux/swapSlice.ts
> +export const getFrom = (state: AppState) => state.swap.from;
This part crash on local run
![image](https://github.com/aryatrading/arya-crypto-web/assets/116554738/68c8f1e2-db3b-443f-9e05-aca651dbf9cd)

2023-05-12 06:56 UTC, AbdallaEmadEldinAbdalla commented on src/components/app/trade/assetTradeFromInput.tsx
> +  }, [asset.symbol, symbol]);
This make app crash locally.
![image](https://github.com/aryatrading/arya-crypto-web/assets/116554738/8be4524d-6be2-42e0-850f-3211c349bc0f)

2023-05-12 06:56 UTC, AbdallaEmadEldinAbdalla commented on src/components/app/trade/assetTradeFromInput.tsx
> +  const onFromSelect = async (elm: any) => {
instead of `any` type plz use `AssetSwapType` that u made.

2023-05-12 06:58 UTC, AbdallaEmadEldinAbdalla commented
@SNuseibeh plz add `?` for all the attr under `asset` on the input. like `asset.symbol` to `asset?.symbol`/

2023-05-15 09:52 UTC, merged