Enhancement/revamp search crw 138
aryatrading/arya-crypto-web pull request #34
Opened 2023-05-11 11:48 UTC by AbdallaEmadEldinAbdalla

[CRW-138](https://techxarya.atlassian.net/browse/CRW-138)
[CRW-139](https://techxarya.atlassian.net/browse/CRW-139)

2023-05-12 12:58 UTC, alex-greenbull commented on src/components/shared/assetSearchInputWithDropdown/index.tsx
> +            {focused && <Col className={clsx("w-[400px] h-[300px] bg-grey-2 top-16 right-0 absolute items-center rounded-md overflow-scroll p-4", styles.list)}>
change h-[300px] to max-h-[300px]
change to overflow-scroll to overflow-auto

goal is to have no scroll bar if no keyword
![Screenshot__001284](https://github.com/aryatrading/arya-crypto-web/assets/58027479/497d7c97-306e-4f29-92a6-7f26fe9bd114)

2023-05-12 12:58 UTC, alex-greenbull commented on src/components/shared/assetSearchInputWithDropdown/index.tsx
> +    const resultLimit = useMemo(() => keyword !== '' ? 50 : 10, [keyword]);
change 10 to 5

2023-05-12 12:59 UTC, alex-greenbull commented on src/components/shared/assetSearchInputWithDropdown/index.tsx
> +                        <span className="w-full mx-4 text-center">No asset with this keyword!<br /><br />{keyword}</span>
Translation

2023-05-15 09:21 UTC, ameer-greenbull requested changes

2023-05-15 09:21 UTC, ameer-greenbull commented on src/components/svg/searchIcon.tsx
>      </svg>
This icon is duplicate use the one used in AssetSelector or remove both and replace with heroIcon

2023-05-15 10:00 UTC, ameer-greenbull approved these changes

2023-05-15 10:01 UTC, merged