Fix/dashboard smart allocation responsivness
aryatrading/arya-crypto-web pull request #37
Opened 2023-05-12 11:04 UTC by almujtabamohammed

2023-05-16 07:05 UTC, AbdallaEmadEldinAbdalla requested changes

2023-05-16 07:05 UTC, AbdallaEmadEldinAbdalla commented on src/components/app/smart-allocation/authed-smart-allocation/authed-smart-alocation.tsx
> +                <SmartAllocationContext.Provider value={{ rebalancingDate, rebalancingFrequency, isLoadingSmartAllocationData: isLoadingSmartAllocationHoldings, getSmartAllocationData: initSmartAlloc
why u used the context API here?

2023-05-17 06:45 UTC, almujtabamohammed commented on src/components/app/dashboard/dashboard.tsx
> +    if (!portfolioHoldings.length)
To prevent setting isLoadingPortfolioHoldings after first load

2023-05-17 06:54 UTC, almujtabamohammed commented on src/components/app/dashboard/dashboard.tsx
> +          <tr>
Because some text are aligned left and some are aligned right

2023-05-17 07:15 UTC, AbdallaEmadEldinAbdalla approved these changes

2023-05-17 07:15 UTC, merged