Edit smart allocation responsive
aryatrading/arya-crypto-web pull request #46
Opened 2023-05-17 13:02 UTC by almujtabamohammed

2023-05-25 12:28 UTC, ameer-greenbull approved these changes

2023-05-25 12:28 UTC, ameer-greenbull commented on src/components/shared/pageLoader/pageLoader.tsx
> +    <Col className="w-full h-[calc(100vh_-_7rem)] md:h-[calc(100vh_-_7rem_-_60px)] items-center justify-center">
suggestion why not use dialog component from radix?

2023-05-29 12:46 UTC, AbdallaEmadEldinAbdalla requested changes
Why most of th `p` tags doesn't have any styling?

2023-05-29 12:46 UTC, AbdallaEmadEldinAbdalla commented on src/components/app/smart-allocation/authed-smart-allocation/smart-allocation-tabs/smart-allocation-holdings-tab/smart-allocation-holdings-tab.tsx
> +                    <tr>
Why we don't create 2 arrays and map to make it more clear

2023-05-29 12:46 UTC, AbdallaEmadEldinAbdalla commented on src/components/app/smart-allocation/authed-smart-allocation/smart-allocation-tabs/smart-allocation-holdings-tab/smart-allocation-holdings-tab.tsx
> +                                    <p>{formatNumber(asset?.available ?? 0)}</p>
We don't need text styling here?

2023-05-29 13:07 UTC, merged