Feature/trade route
aryatrading/arya-crypto-web pull request #49
Opened 2023-05-19 07:20 UTC by SNuseibeh

This PR includes the UI for the trade feature, mobile & web responsive. 

Note: Backend server is down, so testing the functionality will be difficult.

2023-05-19 12:30 UTC, alex-greenbull commented
![Screenshot_httpsarya-crypto-web-git-feature-trade-route-arya-crypto vercel apptrade_001304](https://github.com/aryatrading/arya-crypto-web/assets/58027479/c1f41372-7450-45e1-bd9b-b22652829003)

1 : remove 0 as the default value on all the inputs
2. hide title if no take profit set, same fr SL and trailing

2023-05-19 12:31 UTC, alex-greenbull commented
Missing exchange selector and asset selector

2023-05-19 12:33 UTC, alex-greenbull commented
![Screenshot_httpsarya-crypto-web-git-feature-trade-route-arya-crypto vercel apptrade_001308](https://github.com/aryatrading/arya-crypto-web/assets/58027479/2a7b9fe2-8875-4dfd-9739-b6dce99e7d2e)
follow figma

2023-05-19 12:33 UTC, SNuseibeh commented
> Missing exchange selector and asset selector

the provider selector is a WIP, just having issues with the backend on that matter.

2023-05-26 12:56 UTC, ameer-greenbull requested changes

2023-05-26 12:56 UTC, ameer-greenbull commented on src/components/shared/tables/orderHistoryTable.tsx
> +import { XMarkIcon, TrashIcon } from "@heroicons/react/24/outline";
remove if not using

2023-05-26 12:56 UTC, ameer-greenbull commented on src/components/shared/trailingPicker.tsx
> +    <DropdownMenu.Root>
```suggestion
    <DropdownMenu.Root modal={false}>
```

2023-05-26 12:56 UTC, ameer-greenbull commented on src/pages/trade/index.tsx
> +  }, [symbol, selectedExchange]);
```suggestion
  }, [symbol, selectedExchange, dispatch]);
```

2023-05-26 12:56 UTC, ameer-greenbull commented on src/services/controllers/trade.ts
> +  console.log("open order data >>> ", data);
remove console.log

2023-05-26 12:56 UTC, ameer-greenbull commented on src/components/shared/tables/openOrderTable.tsx
> +                        onClick={() => console.log("close")}
why is this console logging onclick?

2023-05-29 05:48 UTC, merged