fix: Fix and modify some UI component.
aryatrading/arya-crypto-web pull request #71
Opened 2023-06-07 13:51 UTC by AbdallaEmadEldinAbdalla

2023-06-08 12:12 UTC, almujtabamohammed requested changes

2023-06-08 12:12 UTC, almujtabamohammed commented on src/components/app/smart-allocation/authed-smart-allocation/authed-smart-alocation.tsx
> +                    {/* <ExchangeSwitcher canSelectOverall={false} /> */}
Why did you remove this?

2023-06-08 13:11 UTC, AbdallaEmadEldinAbdalla commented on src/components/app/smart-allocation/authed-smart-allocation/authed-smart-alocation.tsx
> +                    {/* <ExchangeSwitcher canSelectOverall={false} /> */}
@almujtabamohammed  it still a draft xD

2023-06-13 12:58 UTC, almujtabamohammed approved these changes

2023-06-13 13:03 UTC, merged