Feature/asset stats crw 354
aryatrading/arya-crypto-web pull request #78
Opened 2023-06-12 06:38 UTC by AbdallaEmadEldinAbdalla

[CRW-354](https://techxarya.atlassian.net/browse/CRW-354)

Done except the charts

2023-06-12 13:38 UTC, almujtabamohammed requested changes

2023-06-12 13:38 UTC, almujtabamohammed commented on src/components/app/asset/assetInformation.tsx
> +import 'react-circular-progressbar/dist/styles.css';
Please move this import to _app.tsx

2023-06-12 13:38 UTC, almujtabamohammed commented on src/components/app/asset/assetInformation.tsx
> +                </svg>
Extract csv to separate file

2023-06-12 13:38 UTC, almujtabamohammed commented on src/components/app/asset/assetInformation.tsx
> +                </svg>
Extract svg

2023-06-13 10:53 UTC, alex-greenbull commented
![Screenshot_arya-crypto-web-git-feature-asset-stats-crw-354-arya-crypto vercel appassetsymbolbtc_001426](https://github.com/aryatrading/arya-crypto-web/assets/58027479/bbd040bc-4b89-4039-812c-513ecf5bc5f1)
 
 change orange to blue

2023-06-13 11:55 UTC, almujtabamohammed requested changes

2023-06-13 11:55 UTC, almujtabamohammed commented on src/components/app/asset/assetInformation.tsx
> +                  <p className="text-4xl font-bold text-blue-1 text-center sm:text-left">{coinstats?.premium ? '12.6' : coinstats?.portfolio_holdings}%</p>
This is causing an error
Error: Objects are not valid as a React child (found: object with keys {day, holding_count}). If you meant to render a collection of children, use an array instead.

2023-06-13 11:58 UTC, almujtabamohammed commented on public/locales/en/asset.json
> +    "todayTrades": "BTC trades today",
This "BTC" should be dynamic based on the asset name

2023-06-15 11:34 UTC, almujtabamohammed approved these changes

2023-06-15 11:36 UTC, merged