Enhancement/revamp trading sales page crw 330
aryatrading/arya-crypto-web pull request #87
Opened 2023-06-13 10:06 UTC by AbdallaEmadEldinAbdalla

[CRW-330](https://techxarya.atlassian.net/browse/CRW-330)

2023-06-13 10:47 UTC, alex-greenbull commented
![Screenshot_arya-crypto-web-git-enhancement-revamp-tradi-d9ea87-arya-crypto vercel appfrtrade_001424](https://github.com/aryatrading/arya-crypto-web/assets/58027479/a1f76c11-523a-4da8-b0fd-5342a99431f8)

This should be a carousell

2023-06-13 10:50 UTC, AbdallaEmadEldinAbdalla commented
> ![Screenshot_arya-crypto-web-git-enhancement-revamp-tradi-d9ea87-arya-crypto vercel appfrtrade_001424](https://user-images.githubusercontent.com/58027479/245451035-a1f76c11-523a-4da8-b0fd-5342a99431f8.png)
> 
> This should be a carousell

Me and AL will work on it

2023-06-14 06:46 UTC, almujtabamohammed requested changes

2023-06-14 06:46 UTC, almujtabamohammed commented on src/components/shared/Testimonials/index.tsx
> +}];
- Add translation
- Move to constants file

2023-06-14 06:46 UTC, almujtabamohammed commented on src/components/shared/Testimonials/index.tsx
> +                                <Col className="items-center bg-offWhite-1 rounded-2xl py-12 px-10 border-4 border-blue-4 h-[250px]">
Remove height, because it doesn't look good on small screens

2023-06-14 07:08 UTC, merged